[build.env]
passthrough = [
    "GITHUB_TOKEN"
]

# workaround for https://github.com/cross-rs/cross/issues/1345
[target.x86_64-unknown-netbsd]
pre-build = [
    "mkdir -p /tmp/netbsd",
    "curl https://cdn.netbsd.org/pub/NetBSD/NetBSD-9.2/amd64/binary/sets/base.tar.xz -O",
    "tar -C /tmp/netbsd -xJf base.tar.xz",
    "cp /tmp/netbsd/usr/lib/libexecinfo.so /usr/local/x86_64-unknown-netbsd/lib",
    "rm base.tar.xz",
    "rm -rf /tmp/netbsd",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "dpkg --configure -a || true",
    "dpkg --add-architecture amd64",
    "DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends musl-tools pkg-config libssl-dev:amd64 -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold"
]

[target.x86_64-unknown-linux-musl.env]
passthrough = [
    "OPENSSL_DIR=/usr",
    "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu",
    "OPENSSL_INCLUDE_DIR=/usr/include",
    "OPENSSL_STATIC=1",
    "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig"
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "dpkg --configure -a || true",
    "dpkg --add-architecture amd64",
    "DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends pkg-config libssl-dev:amd64 -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold"
]

[target.x86_64-unknown-linux-gnu.env]
passthrough = [
    "OPENSSL_DIR=/usr",
    "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu",
    "OPENSSL_INCLUDE_DIR=/usr/include",
    "OPENSSL_STATIC=1",
    "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "dpkg --configure -a || true",
    "dpkg --add-architecture aarch64",
    "DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends pkg-config libssl-dev:aarch64 -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold"
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "OPENSSL_DIR=/usr",
    "OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu",
    "OPENSSL_INCLUDE_DIR=/usr/include",
    "OPENSSL_STATIC=1",
    "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "dpkg --configure -a || true",
    "dpkg --add-architecture aarch64",
    "DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends musl-tools pkg-config libssl-dev:aarch64 -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold"
]

[target.aarch64-unknown-linux-musl.env]
passthrough = [
    "OPENSSL_DIR=/usr",
    "OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu",
    "OPENSSL_INCLUDE_DIR=/usr/include",
    "OPENSSL_STATIC=1",
    "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig"
]
