[build.env]
passthrough = [
    "GITHUB_TOKEN",
    "OPENSSL_DIR",
    "PKG_CONFIG_PATH"
]

# workaround for https://github.com/cross-rs/cross/issues/1345
[target.x86_64-unknown-netbsd]
pre-build = [
    "mkdir -p /tmp/netbsd",
    "curl https://cdn.netbsd.org/pub/NetBSD/NetBSD-9.2/amd64/binary/sets/base.tar.xz -O",
    "tar -C /tmp/netbsd -xJf base.tar.xz",
    "cp /tmp/netbsd/usr/lib/libexecinfo.so /usr/local/x86_64-unknown-netbsd/lib",
    "rm base.tar.xz",
    "rm -rf /tmp/netbsd",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update --yes && apt-get install --yes musl-tools pkg-config openssl libssl-dev",
]
