name: CI/CD Workflow

on:
  push:
    branches:
      - 'master'
  pull_request:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  ci:
    name: CI/CD build
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-freebsd
            skip_tests: true

          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-riscv64
            runs-on: ubuntu-20.04
            target: riscv64gc-unknown-linux-gnu

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - uses: webiny/action-conventional-commits@v1.1.0
        if: matrix.platform.os-name == 'x86_64-unknown-linux-gnu'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: google-github-actions/release-please-action@v4
        id: release
        if: matrix.platform.os-name == 'x86_64-unknown-linux-gnu'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust
          repo-url: opsplane-services/am2am

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Login to Nexus Registry
        uses: docker/login-action@v3
        if: matrix.platform.os-name == 'x86_64-unknown-linux-gnu'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta build
        id: meta
        uses: docker/metadata-action@v4
        if: ${{ !steps.release.outputs.release_created && matrix.platform.os-name == 'x86_64-unknown-linux-gnu' }}
        with:
          images: ghcr.io/${{ github.repository_owner }}/am2am
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest

      - name: Docker meta release
        id: meta_release
        uses: docker/metadata-action@v4
        if: ${{ steps.release.outputs.release_created && matrix.platform.os-name == 'x86_64-unknown-linux-gnu' }}
        with:
          images: ghcr.io/${{ github.repository_owner }}/am2am
          tags: |
            type=ref,event=branch
            type=raw,value=${{ steps.release.outputs.tag_name }}
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: matrix.platform.os-name == 'x86_64-unknown-linux-gnu'
        with:
          driver: docker-container
          driver-opts: image=moby/buildkit:latest

      #- name: Build and push
      #  uses: docker/build-push-action@v3
      #  if: ${{ !steps.release.outputs.release_created && matrix.platform.os-name == 'x86_64-unknown-linux-gnu' }}
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    platforms: linux/amd64,linux/arm64
      #    tags: ${{ steps.meta.outputs.tags }}
      #    labels: ${{ steps.meta.outputs.labels }}
      #    push: ${{ github.event_name != 'pull_request' }}

      #- name: Build and push release
      #  uses: docker/build-push-action@v3
      #  if: ${{ steps.release.outputs.release_created && matrix.platform.os-name == 'x86_64-unknown-linux-gnu' }}
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    tags: ${{ steps.meta_release.outputs.tags }}
      #    labels: ${{ steps.meta_release.outputs.labels }}
      #    push: ${{ github.event_name != 'pull_request' }}
